name: StandaloneWindows64

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        clean: false

    - name: Get the version
      id: get_version
      run: ${{secrets.VERSION_EXTRACT_BAT_PATH}} ${{github.ref}}

    - name: Check Version
      run: echo ${{ steps.get_version.outputs.TAG }}

    - name: Encryption
      shell: cmd
      run: 'copy /Y ${{secrets.ENCRYPT_INFO_SRC}} ${{secrets.ENCRYPT_INFO_DST}}'

    - name: Windows
      shell: cmd
      run: '"C:/Program Files/Unity/Hub/Editor/2021.1.10f1/Editor/Unity.exe" -quit -batchmode -nographics -silent-crashes -logFile - -projectPath ${{secrets.UNITY_PROJECT_PATH}} -executeMethod BuildScripts.BuildStandaloneWindows64 -buildTarget StandaloneWindows64 -locationPathName ${{secrets.EXE_BUILD_PATH}} -githubref ${{github.ref}}'

    - name: Preprocess Inno Scripts
      shell: cmd
      run: ${{secrets.INNO_PREPROCESS_EXE_PATH}} ${{github.ref}}

    - name: Create Installer
      shell: cmd
      run: 'iscc "${{secrets.ISS_PATH}}"'

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{secrets.INSTALLER_PATH}}
        asset_name: RepulserEngine_v${{ steps.get_version.outputs.TAG }}_Setup.exe
        asset_content_type: application/exe